# Generated by Django 3.2 on 2023-06-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_category_comment_genre_rating_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='average_score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
